# Лабораторне заняття №2
Знайомство з бібліотекою **NumPy**.

In [1]:
import numpy as np

## 1 Огляд функцій випадкового вибору

### 1.1 Функція *choice*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.choice.html).

In [2]:
a = ["top", 2, "bottom", 4.5]
size = 10
probs = [0.4, 0.2, 0.1, 0.3]
replace = True
print(np.random.choice(a, size=size, replace=replace, p=probs))

['2' 'bottom' 'top' '4.5' 'top' '4.5' '2' 'top' 'top' 'top']


Згенеруйте одну випадкову цифру, вважаючи їх рівноймовірними.

In [3]:
# Місце для Вашого коду
import numpy as np
number=np.arange(0, 10, 1)
print(number)
print(np.random.choice(number, size=1, replace=False))


[0 1 2 3 4 5 6 7 8 9]
[0]


Згенеруйте випадкову матрицю $4 \times 6$ із рівноймовірних цифр.

In [4]:
# Місце для Вашого коду
number=np.arange(0, 10, 1)
print(number)
mas=(np.random.choice(number, size=24, replace=True))
mas.shape=(4,6)
print(mas)


[0 1 2 3 4 5 6 7 8 9]
[[3 5 3 9 1 4]
 [5 7 8 8 2 7]
 [8 3 8 8 9 6]
 [4 6 7 6 1 7]]


### 1.2 Функція *randint*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.randint.html).

In [5]:
low = 0
high = 5
size = 10
print(np.random.randint(low=low, high=high, size=size))

[3 1 4 2 1 4 1 1 0 4]


Згенеруйте одну випадкову цифру.

In [6]:
# Місце для Вашого коду
low = 0
high = 10
size = 1
print(np.random.randint(low=low, high=high, size=size))


[4]


Згенеруйте випадкову матрицю $4 \times 5$ із двоцифрових чисел.

In [7]:
# Місце для Вашого коду
low = 0
high = 10
size = (4,5)
print(np.random.randint(low=low, high=high, size=size))


[[6 2 2 7 6]
 [7 5 8 9 2]
 [6 7 4 1 0]
 [4 4 7 1 6]]


### 1.3 Функція *sample*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.sample.html).

In [8]:
size = None
print(np.random.sample(size=size))

0.3369603119037976


Згенеруйте випадкову матрицю $3 \times 4$ із чисел з інтервалу $[0, 1)$.

In [8]:
# Місце для Вашого коду
size=(3,4)
print(np.random.sample(size=size))


[[0.83027649 0.33700586 0.38003342 0.27849795]
 [0.13335043 0.36138452 0.77618136 0.44558383]
 [0.80076455 0.5797459  0.1844296  0.1429935 ]]


Згенеруйте 10 випадкових чисел з інтервалу $[a, b)$.

In [10]:
a = 3
b = 5

In [9]:
# Місце для Вашого коду
size=10
k=2*np.random.sample(size=size)+3
print(k)


[4.84931304 4.72057595 3.01859338 4.76268689 3.05333324 3.79419996
 3.25553256 4.96859136 3.13296321 4.01542557]


### 1.4 Функція *shuffle*
Для детальної інформації див. [документацію](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.shuffle.html).

In [12]:
x = np.arange(10)
np.random.shuffle(x)
print(x)

[9 5 3 7 8 1 0 2 6 4]


Перетасуйте матрицю $M$.

In [13]:
M = np.arange(20).reshape((4, 5))
print(M)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [17]:
# Місце для Вашого коду
M = np.arange(20).reshape((4, 5))
np.random.shuffle(M)
print(M)
Mt=np.transpose(M) 
np.random.shuffle(Mt)
print(Mt)


[[10 11 12 13 14]
 [15 16 17 18 19]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]
[[13 18  8  3]
 [10 15  5  0]
 [11 16  6  1]
 [14 19  9  4]
 [12 17  7  2]]


## 2 Відтворюваність результатів
Можна задати початкове значення для генератора. Це зафіксує "випадкову" послідовність.

In [15]:
np.random.seed(42)

In [16]:
print(np.random.randint(10))

6


In [17]:
print(np.random.randint(10))

3


In [18]:
np.random.seed(42)
print(np.random.randint(10))
print(np.random.randint(10))

6
3


In [19]:
np.random.seed(42)
print(np.random.randint(10, size=10))
print(np.random.choice(['t', 'r', 'b', 'l'], size=10))
np.random.seed(42)
print(np.random.randint(10, size=10))
print(np.random.choice(['t', 'r', 'b', 'l'], size=10))

[6 3 7 4 6 9 2 6 7 4]
['l' 'l' 'l' 'b' 'r' 't' 'r' 'l' 'l' 'r']
[6 3 7 4 6 9 2 6 7 4]
['l' 'l' 'l' 'b' 'r' 't' 'r' 'l' 'l' 'r']


## 3 Монетка

### 3.1 За допомогою функції *choice*

In [22]:
p=0.5
n=10
tosses=np.random.choice(["H","T"],p=[p,1-p], size=n)
print(tosses)

['H' 'H' 'T' 'H' 'T' 'T' 'H' 'T' 'H' 'H']


In [23]:
heads = list(tosses).count("H")
tails = list(tosses).count("T")

print("{} heads and {} tails".format(heads,tails))

6 heads and 4 tails


Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [18]:
# Місце для Вашого коду
p=0.5
n=100
tosses=np.random.choice(["H","T"],p=[p,1-p], size=n)
print(tosses)
heads = list(tosses).count("H")
tails = list(tosses).count("T")

print("{} heads and {} tails".format(heads,tails))


['T' 'H' 'H' 'T' 'T' 'T' 'H' 'T' 'T' 'H' 'T' 'H' 'T' 'T' 'H' 'H' 'T' 'T'
 'H' 'H' 'T' 'H' 'T' 'T' 'T' 'T' 'T' 'H' 'H' 'H' 'T' 'T' 'T' 'T' 'H' 'T'
 'H' 'H' 'H' 'H' 'H' 'H' 'T' 'T' 'H' 'T' 'H' 'H' 'H' 'T' 'H' 'T' 'T' 'T'
 'T' 'H' 'T' 'T' 'H' 'H' 'H' 'T' 'H' 'T' 'H' 'H' 'H' 'T' 'T' 'H' 'H' 'T'
 'H' 'H' 'H' 'H' 'T' 'H' 'H' 'T' 'H' 'H' 'T' 'T' 'H' 'T' 'T' 'H' 'T' 'T'
 'H' 'H' 'H' 'T' 'T' 'H' 'T' 'H' 'H' 'T']
51 heads and 49 tails


### 3.2 За допомогою функції *randint*
Реалізуйте симуляцію підкидань монетки за допомогою функції **randint**. Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [19]:
# Місце для Вашого коду
low = 0
high = 2
size = 100
a=(np.random.randint(low=low, high=high, size=size))
print(a)
heads = list(a).count(0)
tails = list(a).count(1)

print("{} heads and {} tails".format(heads,tails))


[0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 1 1 1 0 0 1 1 0 0 1 1 1 0 1 0 1 0 0 0 1 0 0
 1 1 1 1 0 0 0 1 1 0 1 1 0 0 0 1 0 1 1 1 1 1 0 0 0 0 1 1 1 1 0 1 1 0 1 1 0
 0 0 1 1 1 1 1 1 0 1 0 1 1 0 0 0 1 0 1 0 1 1 1 0 1 0]
49 heads and 51 tails


### 3.3 За допомогою функції *sample*
Реалізуйте симуляцію підкидань монетки за допомогою функції **sample**. Просимулюйте $100$ підкидань монетки та підрахуйте кількість кожної із сторін.

In [20]:
# Місце для Вашого коду
size =100
import numpy as np
a=(np.random.sample(size=size))

print(a)
#b=a>0.5
#print(b)
def f (a):
   if a>0.5:
        c='H'
   else:
        c='T'
   return(c)
f1=np.vectorize(f)
print(f1(a))


[0.21391259 0.80936893 0.19800154 0.12865395 0.57649625 0.00449989
 0.35368863 0.54789551 0.61591957 0.96453641 0.86577997 0.41859425
 0.40437738 0.35328163 0.67510829 0.13013703 0.23742804 0.98823519
 0.13672224 0.52364137 0.78487555 0.56375188 0.44142807 0.45304899
 0.09698723 0.34533663 0.32371986 0.74484471 0.59795838 0.59725033
 0.94399632 0.02787011 0.91447719 0.5124815  0.51436452 0.30177866
 0.69866059 0.35869746 0.33029024 0.75554233 0.01705823 0.5787083
 0.17183594 0.94905508 0.99727753 0.15033138 0.31744936 0.23107401
 0.6693292  0.81191885 0.27934789 0.03063866 0.54805767 0.99074798
 0.18716921 0.69754146 0.46313618 0.77307705 0.1753158  0.03014099
 0.12540184 0.8342355  0.76391582 0.51323505 0.65678016 0.05883782
 0.77878346 0.98025084 0.16122668 0.16553937 0.24992468 0.94433621
 0.43210364 0.39412427 0.52041929 0.05108943 0.82406717 0.92426696
 0.44338458 0.14131849 0.1668461  0.50609318 0.1036918  0.92037169
 0.67727578 0.95329734 0.99803847 0.55976839 0.10641991 0.55767

### 3.4 Задача
Знайдіть емпіричну ймовірність герба у симуляціях підкидання монетки $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [21]:
# Місце для Вашого коду
low = 0
high = 2
list6=[10,50,100,250,500,1000,2500,5000,10000]
for i in list6:
    size = i
    a=(np.random.randint(low=low, high=high, size=size))
    #print(a)
    heads = list(a).count(0)
    tails = list(a).count(1)
    print(i, tails/(heads+tails))


10 0.6
50 0.62
100 0.49
250 0.536
500 0.49
1000 0.496
2500 0.5004
5000 0.4938
10000 0.4973


## 4 Гральний кубик
### 4.1 Реалізація симуляцій
Реалізуйте симуляцію кидків грального кубика за допомогою функції **???**. Просимулюйте $60$ кидків кубика та підрахуйте кількість кожної із сторін.

In [23]:
# Місце для Вашого коду
low = 1
high = 7
size = 100
a=(np.random.randint(low=low, high=high, size=size))
print(a)
d=dict()
for i in range (1, 7):
    d_= list(a).count(i)
    d.update({i:d_})


print(d)


[2 4 6 3 2 1 6 1 3 2 4 5 6 6 2 5 6 2 2 1 4 4 2 2 5 6 2 6 2 2 1 6 2 4 5 2 4
 5 4 2 5 1 3 6 6 1 3 6 2 5 1 6 2 3 3 4 4 5 5 3 4 4 5 3 2 5 6 1 5 4 3 5 6 3
 6 2 6 4 2 6 1 2 4 1 2 3 1 6 4 5 2 3 1 4 2 5 5 4 5 6]
{1: 12, 2: 23, 3: 12, 4: 17, 5: 17, 6: 19}


### 4.2 Задача
Знайдіть емпіричну ймовірність кожної сторони у симуляціях кидання грального кубика $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [22]:
# Місце для Вашого коду
low = 0
high = 7
list7=[10,50,100,250,500,1000,2500,5000,10000]
for i in list7:
    size = i
    a=(np.random.randint(low=low, high=high, size=size))
    d=dict()
    probability={}
    for j in range (1, 7):
        d_= list(a).count(j)
        d.update({j:d_})
        d_p=d_/i
        probability.update({j:d_p})
    print(d, probability)


{1: 2, 2: 2, 3: 1, 4: 2, 5: 0, 6: 2} {1: 0.2, 2: 0.2, 3: 0.1, 4: 0.2, 5: 0.0, 6: 0.2}
{1: 8, 2: 5, 3: 3, 4: 8, 5: 6, 6: 7} {1: 0.16, 2: 0.1, 3: 0.06, 4: 0.16, 5: 0.12, 6: 0.14}
{1: 17, 2: 10, 3: 15, 4: 9, 5: 13, 6: 16} {1: 0.17, 2: 0.1, 3: 0.15, 4: 0.09, 5: 0.13, 6: 0.16}
{1: 32, 2: 35, 3: 31, 4: 33, 5: 36, 6: 38} {1: 0.128, 2: 0.14, 3: 0.124, 4: 0.132, 5: 0.144, 6: 0.152}
{1: 64, 2: 64, 3: 93, 4: 64, 5: 86, 6: 65} {1: 0.128, 2: 0.128, 3: 0.186, 4: 0.128, 5: 0.172, 6: 0.13}
{1: 139, 2: 136, 3: 142, 4: 139, 5: 141, 6: 140} {1: 0.139, 2: 0.136, 3: 0.142, 4: 0.139, 5: 0.141, 6: 0.14}
{1: 382, 2: 320, 3: 336, 4: 383, 5: 344, 6: 379} {1: 0.1528, 2: 0.128, 3: 0.1344, 4: 0.1532, 5: 0.1376, 6: 0.1516}
{1: 738, 2: 664, 3: 697, 4: 667, 5: 703, 6: 742} {1: 0.1476, 2: 0.1328, 3: 0.1394, 4: 0.1334, 5: 0.1406, 6: 0.1484}
{1: 1426, 2: 1443, 3: 1444, 4: 1398, 5: 1403, 6: 1438} {1: 0.1426, 2: 0.1443, 3: 0.1444, 4: 0.1398, 5: 0.1403, 6: 0.1438}


## 5 Колода карт
### 5.1 Реалізація

In [30]:
# Визначимо номінали, масті та карти
Ranks = {'1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K'}
Suits = {'♢', '♠', '♣', '♡'}
# Створимо колоду карт
Cards = [(Rank, Suit) for Rank in Ranks for Suit in Suits]
print(Cards)

[('3', '♣'), ('3', '♠'), ('3', '♡'), ('3', '♢'), ('7', '♣'), ('7', '♠'), ('7', '♡'), ('7', '♢'), ('9', '♣'), ('9', '♠'), ('9', '♡'), ('9', '♢'), ('5', '♣'), ('5', '♠'), ('5', '♡'), ('5', '♢'), ('6', '♣'), ('6', '♠'), ('6', '♡'), ('6', '♢'), ('J', '♣'), ('J', '♠'), ('J', '♡'), ('J', '♢'), ('4', '♣'), ('4', '♠'), ('4', '♡'), ('4', '♢'), ('Q', '♣'), ('Q', '♠'), ('Q', '♡'), ('Q', '♢'), ('8', '♣'), ('8', '♠'), ('8', '♡'), ('8', '♢'), ('10', '♣'), ('10', '♠'), ('10', '♡'), ('10', '♢'), ('1', '♣'), ('1', '♠'), ('1', '♡'), ('1', '♢'), ('2', '♣'), ('2', '♠'), ('2', '♡'), ('2', '♢'), ('K', '♣'), ('K', '♠'), ('K', '♡'), ('K', '♢')]


In [31]:
# Інший вівід результату
print(', '.join([(card[0] + card[1]) for card in Cards]))

3♣, 3♠, 3♡, 3♢, 7♣, 7♠, 7♡, 7♢, 9♣, 9♠, 9♡, 9♢, 5♣, 5♠, 5♡, 5♢, 6♣, 6♠, 6♡, 6♢, J♣, J♠, J♡, J♢, 4♣, 4♠, 4♡, 4♢, Q♣, Q♠, Q♡, Q♢, 8♣, 8♠, 8♡, 8♢, 10♣, 10♠, 10♡, 10♢, 1♣, 1♠, 1♡, 1♢, 2♣, 2♠, 2♡, 2♢, K♣, K♠, K♡, K♢


In [32]:
# Або згрупувавши по мастях
for suit in Suits:
    print(", ".join([(suit+rank) for rank in Ranks]))

♣3, ♣7, ♣9, ♣5, ♣6, ♣J, ♣4, ♣Q, ♣8, ♣10, ♣1, ♣2, ♣K
♠3, ♠7, ♠9, ♠5, ♠6, ♠J, ♠4, ♠Q, ♠8, ♠10, ♠1, ♠2, ♠K
♡3, ♡7, ♡9, ♡5, ♡6, ♡J, ♡4, ♡Q, ♡8, ♡10, ♡1, ♡2, ♡K
♢3, ♢7, ♢9, ♢5, ♢6, ♢J, ♢4, ♢Q, ♢8, ♢10, ♢1, ♢2, ♢K


In [33]:
# Перемішаємо колоду
np.random.shuffle(Cards)

print(Cards)

[('Q', '♠'), ('10', '♡'), ('3', '♡'), ('2', '♠'), ('2', '♣'), ('10', '♢'), ('J', '♡'), ('1', '♢'), ('9', '♡'), ('3', '♣'), ('6', '♡'), ('Q', '♡'), ('K', '♣'), ('8', '♠'), ('J', '♠'), ('7', '♣'), ('K', '♡'), ('8', '♣'), ('5', '♣'), ('Q', '♢'), ('J', '♣'), ('J', '♢'), ('4', '♡'), ('1', '♡'), ('5', '♡'), ('5', '♢'), ('1', '♣'), ('1', '♠'), ('9', '♠'), ('10', '♣'), ('9', '♢'), ('2', '♢'), ('6', '♠'), ('Q', '♣'), ('10', '♠'), ('7', '♠'), ('2', '♡'), ('K', '♢'), ('8', '♢'), ('6', '♣'), ('K', '♠'), ('8', '♡'), ('7', '♢'), ('7', '♡'), ('4', '♢'), ('6', '♢'), ('3', '♠'), ('4', '♠'), ('9', '♣'), ('5', '♠'), ('4', '♣'), ('3', '♢')]


### 5.2 Задача
Знайдіть емпіричну ймовірність карти парного числа (2, 4, 6, 8, 10) у симуляціях вибору однієї карти з колоди 52 карт $n = 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000$ разів.

In [24]:
# Місце для Вашого коду
list8=[10,50,100,250,500,1000,2500,5000,10000]
par=(2, 4, 6, 8, 10) 
for i in list8:
    n=0
    for j in range(i):
         
        np.random.shuffle(Cards)
        card=Cards[0]
        if i==10:print(card)
        try:
            if int(card[0]) in par:
                n+=1
        except Exception:
            pass
            
    print(i, n, n/i)


NameError: name 'Cards' is not defined

### 5.3 Задача
Випадковим чином роздайте колоду з 52 карт чотирьом гравцям (кожному по 13 карт) так, щоб кожен з них мав 4 карти однієї масті та по 3 карти інших мастей. Наприклад, {♣5, ♣10, ♣8, ♣4, ♠4, ♠J, ♠3, ♢Q, ♢7, ♢K, ♡9, ♡1, ♡5}.

In [25]:
# Місце для Вашого коду
Ranks = {'1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K'}
heart = [(Rank,'♡') for Rank in Ranks]
diamonds= [(Rank,'♢') for Rank in Ranks]
clubs=[(Rank,'♣') for Rank in Ranks]
pikes=[(Rank,'♠') for Rank in Ranks]
All_suits=[heart, diamonds, clubs, pikes]
player1=[]
player2=[]
player3=[]
player4=[]
for j in All_suits:
   
    np.random.shuffle(j)
    for k in range (0, 3):
        player1.append(str(j[k]))
        player2.append(str(j[k+3]))
        player3.append(str(j[k+6]))
        player4.append(str(j[k+9]))
    np.random.shuffle([heart, diamonds, clubs, pikes])


tabble=[player1, player2, player3, player4]
q=0
for i in tabble:
    i.append(All_suits[q][12])
    q+=1
    print('player'+str(q), i)


player1 ["('K', '♡')", "('10', '♡')", "('1', '♡')", "('8', '♢')", "('7', '♢')", "('3', '♢')", "('8', '♣')", "('6', '♣')", "('Q', '♣')", "('J', '♠')", "('6', '♠')", "('1', '♠')", ('6', '♡')]
player2 ["('9', '♡')", "('7', '♡')", "('J', '♡')", "('4', '♢')", "('J', '♢')", "('6', '♢')", "('10', '♣')", "('1', '♣')", "('7', '♣')", "('7', '♠')", "('9', '♠')", "('Q', '♠')", ('10', '♢')]
player3 ["('3', '♡')", "('Q', '♡')", "('2', '♡')", "('K', '♢')", "('5', '♢')", "('9', '♢')", "('K', '♣')", "('4', '♣')", "('J', '♣')", "('10', '♠')", "('3', '♠')", "('2', '♠')", ('5', '♣')]
player4 ["('8', '♡')", "('4', '♡')", "('5', '♡')", "('2', '♢')", "('1', '♢')", "('Q', '♢')", "('2', '♣')", "('9', '♣')", "('3', '♣')", "('5', '♠')", "('K', '♠')", "('4', '♠')", ('8', '♠')]


### 5.4 Задача
Випадковим чином роздайте колоду з 52 карт чотирьом гравцям (кожному по 13 карт) так, щоб кожен з них мав від 2 до 5 карт кожної масті. Наприклад, {♣5, ♣10, ♣8, ♣4, ♠4, ♠J, ♠3, ♢Q, ♣7, ♢K, ♡9, ♡1, ♡5}.

In [26]:
# Місце для Вашого коду
Ranks = {'1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K'}
heart = [(Rank,'♡') for Rank in Ranks]
diamonds= [(Rank,'♢') for Rank in Ranks]
clubs=[(Rank,'♣') for Rank in Ranks]
pikes=[(Rank,'♠') for Rank in Ranks]
All_suits=[heart, diamonds, clubs, pikes]
player1=[]
player2=[]
player3=[]
player4=[]
other=[]
for j in All_suits:
   
    np.random.shuffle(j)
    for k in range (0, 2):
        player1.append(str(j[k]))
        player2.append(str(j[k+2]))
        player3.append(str(j[k+4]))
        player4.append(str(j[k+6]))
    for k in range (8, 13):
        other.append(str(j[k]))
Flag=False
chance=0
while Flag==False:
    chance+=1
    Flag=True
    np.random.shuffle(other)
    l1=other[0:5]
    bubn=0
    tref=0
    pik=0
    cherv=0
    for j in l1:
        if j[0]=='♠':
            pik+=1
        elif j[0]=='♣':
            tref+=1
        elif j[0]=='♢':
            bubn+=1
        elif j[0]=='♡':
            cherv+=1
    if max(pik, cherv, bubn, tref)>3:
        Flag=False
        continue
    l2=other[5:10]
    bubn=0
    tref=0
    pik=0
    cherv=0
    for j in l2:
        if j[0]=='♠':
            pik+=1
        elif j[0]=='♣':
            tref+=1
        elif j[0]=='♢':
            bubn+=1
        elif j[0]=='♡':
            cherv+=1
    if max(pik, cherv, bubn, tref)>3:
        Flag=False
        continue
    l3=other[10:15]
    bubn=0
    tref=0
    pik=0
    cherv=0
    for j in l3:
        if j[0]=='♠':
            pik+=1
        elif j[0]=='♣':
            tref+=1
        elif j[0]=='♢':
            bubn+=1
        elif j[0]=='♡':
            cherv+=1
    if max(pik, cherv, bubn, tref)>3:
        Flag=False
        continue
    l4=other[15:20]
    bubn=0
    tref=0
    pik=0
    cherv=0
    for j in l4:
        if j[0]=='♠':
            pik+=1
        elif j[0]=='♣':
            tref+=1
        elif j[0]=='♢':
            bubn+=1
        elif j[0]=='♡':
            cherv+=1
            
    if max(pik, cherv, bubn, tref)>3:
        Flag=False
        continue


print('chance', chance)
for k in range (0, 5):
        player1.append(str(l1[k]))
        player2.append(str(l2[k]))
        player3.append(str(l3[k]))
        player4.append(str(l4[k]))

tabble=[player1, player2, player3, player4]
q=0
ind=[8, 8, 8, 8]
for i in tabble:
    #for ii in range(0,4):
        #low = 0
        #high = min(13-len(tabble[q]), 13-ind[ii], 3)+1
        #size = 1
        #alpha=int(np.random.randint(low=low, high=high, size=size))
        #if ii==3:
        #    alpha=high
        #print(alpha)
        #for iii in range(ind[ii], ind[ii]+alpha):
        #    i.append(All_suits[ii][iii])
        #ind[ii]+=alpha
    #take1=
    
    #i.append(All_suits[q][12])
    q+=1
    print('player'+str(q), i)


chance 1
player1 ["('4', '♡')", "('5', '♡')", "('5', '♢')", "('7', '♢')", "('5', '♣')", "('4', '♣')", "('K', '♠')", "('1', '♠')", "('9', '♠')", "('J', '♣')", "('K', '♢')", "('9', '♢')", "('6', '♡')"]
player2 ["('J', '♡')", "('8', '♡')", "('Q', '♢')", "('4', '♢')", "('2', '♣')", "('Q', '♣')", "('4', '♠')", "('8', '♠')", "('10', '♣')", "('3', '♡')", "('9', '♣')", "('6', '♢')", "('Q', '♠')"]
player3 ["('Q', '♡')", "('K', '♡')", "('8', '♢')", "('J', '♢')", "('8', '♣')", "('3', '♣')", "('10', '♠')", "('3', '♠')", "('7', '♡')", "('10', '♡')", "('2', '♢')", "('2', '♠')", "('9', '♡')"]
player4 ["('1', '♡')", "('2', '♡')", "('1', '♢')", "('10', '♢')", "('7', '♣')", "('1', '♣')", "('J', '♠')", "('7', '♠')", "('3', '♢')", "('K', '♣')", "('5', '♠')", "('6', '♣')", "('6', '♠')"]
